import type { Metadata } from "next";

import { FooterSection } from "./_homeComponent/FooterSection";
import { Header } from "./_component/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      {children}
      <FooterSection />
    </>
  );
}