import type { Metadata } from "next";
import { Header } from "@/component/Header";
import { FooterSection } from "./home/component/FooterSection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      {children}
      <FooterSection />
    </>
  );
}